version: '1'

networks:
  danil-net:

services:
  db:
    networks: [danil-net]
    container_name: mysql-container
    image: mysql:8.0
    environment:

      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: insurance-calculator-db
    ports:
      - "3000:3306"

  insurance-calculator-app:
    networks: [danil-net]
    container_name: insurance-calculator
    image: insurance-calculator:1.0.4
    ports:
      - "8080:8080"
    depends_on:
      - db

